ALTER TABLE users
ADD COLUMN IF NOT EXISTS availability TEXT;

ALTER TABLE study_groups
ADD COLUMN IF NOT EXISTS modality VARCHAR(30) DEFAULT 'Virtual',
ADD COLUMN IF NOT EXISTS university VARCHAR(150),
ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);
